services:
  traefik:
    image: traefik:v3.7
    command:
      - --providers.docker=true
      - --api.insecure=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: postgres:18
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - dev-app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080

  backend:
    build:
      context: backend
    command: fastapi dev --host 0.0.0.0 --root-path /api
    tty: true
    restart: always
    develop:
      watch:
        - action: sync
          path: backend/app
          target: usr/src/app
    env_file:
      - .env
    environment:
      - LOCALHOST_MODE=False
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=PathPrefix(`/api`)
      - traefik.http.middlewares.backend-strip.stripprefix.prefixes=/api
      - traefik.http.routers.backend.middlewares=backend-strip
      
  frontend:
    build:
      context: frontend
    command: npm run dev -- --host=0.0.0.0
    develop:
      watch:
        - action: sync
          path: frontend/app
          target: /app/app
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=!PathPrefix(`/api`)
    

volumes:
  dev-app-db-data: