"""v0.4

Revision ID: 5507db89a277
Revises: 
Create Date: 2026-09-07 09:28:31.968154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5507db89a277'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions_table',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_access', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('days_table',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hours', sa.LargeBinary(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], ),
    sa.PrimaryKeyConstraint('date', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('days_table')
    op.drop_table('users_table')
    op.drop_table('sessions_table')
    # ### end Alembic commands ###
